import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,stepWorld,assertWorld,DEFAULT_CONFIG,inheritTraits,hash,normal,restoreRecord,branchWorld,gini} from '../lib/simulation/engine.ts';
import type {WorldState,ExperimentRecord} from '../lib/simulation/types.ts';
const make=()=>createWorld({...DEFAULT_CONFIG,population:160,years:300});
function run(w:WorldState,n:number){for(let i=0;i<n;i++){stepWorld(w);assertWorld(w);}return w;}
const record=(w:WorldState):ExperimentRecord=>({version:1,name:'test',savedAt:'2026-09-09',world:w});
void test('same seed reproduces the complete world',()=>assert.deepEqual(run(make(),120),run(make(),120)));
void test('save and restore resumes the exact random stream',()=>{const a=run(make(),37);const b=restoreRecord(JSON.parse(JSON.stringify(record(a))));assert.deepEqual(run(a,100),run(b,100));});
void test('wealth scenarios retain the exact people, random state, and total cash',()=>{const a=make(),b=createWorld({...a.config,wealthMode:'unequal'});assert.equal(a.rng,b.rng);assert.deepEqual(a.people.map(p=>[p.age,p.base,p.parents,p.skills]),b.people.map(p=>[p.age,p.base,p.parents,p.skills]));assert.ok(Math.abs(b.people.reduce((s,p)=>s+p.cash,0)-a.initialCash)<1e-7);assert.equal(gini(a.people.map(p=>p.cash)),0);assert.ok(gini(b.people.map(p=>p.cash))>.3);});
void test('300 years preserves population, money, capital accounting, and valid employment',()=>{const w=run(make(),3600);assert.equal(w.people.length,160);assert.ok(w.nextId>700);assert.ok(w.history.at(-1)!.mobilitySamples>30);assert.ok(w.history.some(f=>f.employment>0));});
void test('annual plasticity and lifetime bounds, including extreme initial traits',()=>{const w=make();for(const p of w.people){p.base[0]=100;p.traits[0]=100;p.base[1]=0;p.traits[1]=0;}for(let y=0;y<40;y++){const before=new Map(w.people.map(p=>[p.id,[...p.traits]]));run(w,12);for(const p of w.people){const a=before.get(p.id);if(a)for(let i=0;i<8;i++)assert.ok(Math.abs(p.traits[i]-a[i])<=.5+1e-8);}}});
void test('birth genetics approximately maintain variance under random mating',()=>{const rng={rng:hash('genetics')};let a=Array.from({length:8000},()=>50+15*normal(rng));for(let gen=0;gen<8;gen++){a=a.map((_,i)=>inheritTraits([a[i]],[a[(i*73+17)%a.length]],.6,rng)[0]);}const mean=a.reduce((s,x)=>s+x,0)/a.length;const sd=Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/a.length);assert.ok(mean>49&&mean<51);assert.ok(sd>13.5&&sd<16.5);});
void test('inheritance transfers an estate once and releases deceased employers',()=>{const w=make();const p=w.people[0],heir=w.people[1];p.age=959;p.children=[heir.id];w.family[p.id].children=[heir.id];p.capital=40;w.people[2].employer=p.id;const estate=p.cash;const id=p.id;stepWorld(w);assertWorld(w);assert.ok(!w.people.some(x=>x.id===id));assert.equal(w.family[id].death,1);assert.ok(w.people.every(x=>x.employer!==id));assert.ok(w.history.at(-1)!.ledger.inheritanceTransferred>=estate);assert.ok(heir.inheritanceReceived>=estate+40);stepWorld(w);assertWorld(w);assert.equal(heir.inheritanceReceived,0);});
void test('no heirs and zero inheritance redistribute rather than deleting resources',()=>{const w=make();w.config.inheritance=0;w.people[0].age=959;w.people[0].children=[];w.people[0].capital=100;run(w,24);});
void test('no working age sellers can continue through unmet demand',()=>{const w=make();w.people.forEach(p=>p.age=100);run(w,12);assert.ok(w.history.at(-1)!.markets.every(m=>m.volume===0));assert.equal(w.history.at(-1)!.satisfaction,0);});
void test('zero cash buyers do not borrow, cash can flow from the wealth holder',()=>{const w=make();w.people.forEach(p=>p.cash=0);w.people[0].cash=w.initialCash;run(w,60);assert.ok(w.people.every(p=>p.cash>=-1e-7));});
void test('a no-change fork remains identical and a changed fork leaves original untouched',()=>{const a=run(make(),24);const b=branchWorld(a,{});run(a,60);run(b,60);assert.deepEqual(a.people,b.people);const c=branchWorld(a,{inheritance:0});assert.equal(a.config.inheritance,1);assert.equal(c.config.inheritance,0);assert.throws(()=>branchWorld(a,{wealthMode:'unequal'}));});
void test('invalid config and broken saved accounts are rejected',()=>{assert.throws(()=>createWorld({...DEFAULT_CONFIG,population:0}));const w=make();w.people[0].cash=-20;assert.throws(()=>restoreRecord(record(w)));});
