'use client';
import {useMemo} from 'react';
import {AreaChart,Area,LineChart,Line,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import type {Snapshot,MetricFrame,Person,PersonPoint} from '@/lib/simulation/types';
import {wealth} from '@/lib/simulation/engine';
import {buildWealthHistogram} from '@/lib/simulation/histogram';

export const fmt=(n:number,d=1)=>Number.isFinite(n)?(Math.abs(n)<1e-8?0:n).toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
export const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const colors=['#d7e1cf','#a0c290','#66a181','#2f806d','#125640'];
const grid={stroke:'#e9eeeb',strokeDasharray:'3 5'};
const tip={border:'1px solid #dfe8e0',borderRadius:10,fontSize:12,boxShadow:'0 8px 25px #162f2310'};
const tick={fontSize:12,fill:'#65766b'};
export function PopulationPlot({data,onSelect,axis='talent'}:{data:Snapshot;onSelect:(id:number)=>void;axis?:string}){
 const dots=useMemo(()=>{const sorted=data.people.map(p=>wealth(p,{markets:data.frame.markets})).sort((a,b)=>a-b);const cut=[.2,.4,.6,.8].map(x=>sorted[Math.floor(sorted.length*x)]);const max=sorted.at(-1)??100;return data.people.map(p=>{const v=wealth(p,{markets:data.frame.markets});const level=max-(sorted[0]??0)<1e-6?2:cut.findIndex(c=>v<=c);return {p,v,x:48+p.traits[0]*6.4,y:axis==='wealth'?272-Math.log10(1+v)/Math.max(1,Math.log10(1+max))*238:272-p.traits[1]*2.38,c:colors[level<0?4:level]};});},[data.people,data.frame.markets,axis]);
 return <div className="population-plot"><svg viewBox="0 0 730 316" aria-label="个体散点图，点击个体查看详情，也可以在个体列表中查询"><defs><linearGradient id="plotFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f0f5e9"/><stop offset="100%" stopColor="#fbfcfa"/></linearGradient></defs><rect x="48" y="32" width="640" height="240" fill="url(#plotFade)" rx="3"/>{[0,20,40,60,80,100].map(t=><g key={t}><line x1={48+t*6.4} x2={48+t*6.4} y1="32" y2="272" stroke="#dee8da" strokeDasharray="2 5"/><line x1="48" x2="688" y1={272-t*2.4} y2={272-t*2.4} stroke="#dee8da" strokeDasharray="2 5"/><text x={48+t*6.4} y="291" textAnchor="middle" className="axis-label">{t}</text>{axis==='talent'&&<text x="32" y={276-t*2.4} textAnchor="end" className="axis-label">{t}</text>}</g>)}<text x="51" y="17" className="axis-title">{axis==='wealth'?'财富 · 对数刻度':'记忆力'}</text><text x="687" y="311" textAnchor="end" className="axis-title">思考能力</text>{dots.map(({p,v,x,y,c})=><circle key={p.id} cx={x} cy={y} r={data.tracked.includes(p.id)?4:2.35} fill={c} fillOpacity={.65} stroke={data.tracked.includes(p.id)?'#d4ec69':'none'} strokeWidth="2" className="person-dot" onClick={()=>onSelect(p.id)}><title>{`#${p.id} · ${Math.floor(p.age/12)} 岁 · 财富 ${fmt(v)} · 思考 ${fmt(p.traits[0])} · 记忆 ${fmt(p.traits[1])}`}</title></circle>)}</svg><div className="plot-legend"><span>每个点，都是一个人</span><div><span>财富低</span>{colors.map(c=><i key={c} style={{background:c}}/>)}<span>高</span></div></div></div>;
}
export function InequalityChart({history,baseline}:{history:MetricFrame[];baseline?:MetricFrame[]}){
 const bm=new Map(baseline?.map(f=>[f.month,f.gini]));const rows=history.map(f=>({year:f.month/12,gini:f.gini,base:bm.get(f.month)}));
 if(rows.length<2)return <div className="chart-empty"><span className="empty-curve">⌁</span><p>差距从这里开始记录</p><small>运行后查看财富基尼系数的变化</small></div>;
 return <ResponsiveContainer width="100%" height={222} minWidth={0}><AreaChart data={rows} margin={{top:12,right:5,left:-20,bottom:0}}><defs><linearGradient id="giniFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7dae82" stopOpacity={.25}/><stop offset="1" stopColor="#7dae82" stopOpacity={0}/></linearGradient></defs><CartesianGrid {...grid} vertical={false}/><XAxis dataKey="year" tick={tick} axisLine={false} tickLine={false} tickFormatter={x=>`${fmt(x,0)}年`}/><YAxis domain={[0,1]} tick={tick} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} formatter={v=>fmt(Number(v),3)} labelFormatter={x=>`第 ${fmt(Number(x),1)} 年`}/><Area name="当前世界" type="monotone" dataKey="gini" stroke="#287c63" fill="url(#giniFill)" strokeWidth={2} isAnimationActive={false}/>{baseline&&<Area name="原始规则" dataKey="base" stroke="#a5a58b" strokeDasharray="5 4" fill="none" strokeWidth={2} isAnimationActive={false}/>}</AreaChart></ResponsiveContainer>;
}
export function WealthHistogram({people,markets}:{people:Person[];markets:MetricFrame['markets']}){
 const {bins:rawBins,invalidCount}=buildWealthHistogram(people.map(p=>wealth(p,{markets})));const bins=rawBins.map(bin=>({...bin,label:fmt(bin.lower,0)}));
 return <>{invalidCount>0&&<p className="model-note" role="alert">有 {invalidCount} 个异常财富值未计入图表。</p>}<ResponsiveContainer width="100%" height={210} minWidth={0}><BarChart data={bins} margin={{top:12,right:6,left:-16,bottom:0}}><CartesianGrid {...grid} vertical={false}/><XAxis dataKey="label" tick={tick} axisLine={false} tickLine={false} interval={3}/><YAxis tick={tick} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} formatter={v=>[`${String(v)} 人`,'人数']} labelFormatter={x=>`财富区间起点 ${String(x)}`}/><Bar dataKey="count" fill="#76a882" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></>;
}
export function MarketHistory({history,kind}:{history:MetricFrame[];kind:'price'|'share'}){
 const rows=history.map(f=>({year:f.month/12,a:kind==='price'?f.markets[0].price:f.markets[0].topShare*100,b:kind==='price'?f.markets[1].price:f.markets[1].topShare*100,c:kind==='price'?f.markets[2].price:f.markets[2].topShare*100}));
 return <ResponsiveContainer width="100%" height={255} minWidth={0}><LineChart data={rows} margin={{top:12,right:10,left:-12,bottom:0}}><CartesianGrid {...grid} vertical={false}/><XAxis dataKey="year" tick={tick} axisLine={false} tickLine={false} tickFormatter={x=>`${fmt(x,0)}年`}/><YAxis tick={tick} axisLine={false} tickLine={false} domain={kind==='share'?[0,100]:['auto','auto']}/><Tooltip contentStyle={tip} formatter={v=>`${fmt(Number(v),2)}${kind==='share'?'%':''}`} labelFormatter={x=>`第 ${fmt(Number(x),1)} 年`}/>{(['a','b','c'] as const).map((k,i)=><Line key={k} type="monotone" name={['生活产出','学习产出','生产增益'][i]} dataKey={k} stroke={['#337e61','#a1b94f','#6890ac'][i]} strokeWidth={2} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer>;
}
export function PersonalHistory({points}:{points:PersonPoint[]}){
 return <ResponsiveContainer width="100%" height={180} minWidth={0}><LineChart data={points.map(p=>({...p,year:p.month/12}))} margin={{top:8,right:8,left:-20,bottom:0}}><CartesianGrid {...grid} vertical={false}/><XAxis dataKey="year" tick={tick} tickFormatter={x=>`${fmt(x,1)}年`}/><YAxis tick={tick}/><Tooltip contentStyle={tip}/><Line dataKey="cash" name="现金" stroke="#2c8269" dot={false} isAnimationActive={false}/><Line dataKey="capital" name="资本数量" stroke="#a1b94f" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>;
}
